

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\ntdisp.obj \
 $(OBJ_PATH)\$O\ndisbind.obj \
 $(OBJ_PATH)\$O\recv.obj \
 $(OBJ_PATH)\$O\send.obj \
 $(OBJ_PATH)\$O\debug.obj \
 $(OBJ_PATH)\$O\excallbk.obj \


_RES_FILE=$(OBJ_PATH)\$O\ndisprot.res
PRECOMPILED_INCLUDE_BASENAME=precomp.h




# lowercased
BASEDIR=d:\winddk\7600.16385.1
OBJECT_ROOT=d:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=f:\wb_net\ndis
OBJ_PATH=f:\wb_net\ndis
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
